use std::fmt::Display;

// Would it be better to just have it as a singular enum, or a trait?

/// A trait meant to unify the way in which parts of the program are printed
pub trait Formattable {
    fn to_fmt(&self) -> Formatted;
    // fn to_general(fmtted: Formatted) -> Formatted {
    //     match fmtted {}
    // }
}

//TEST: May change in form but a general print format is needed
/// Enum that depicts any language needed identifiers in a unified form
#[derive(Debug)]
pub enum Formatted {
    I8,
    U8,
    I16,
    U16,
    F16,
    I32,
    U32,
    F32,
    I64,
    U64,
    F64,
    I128,
    U128,
    F128,
    Integer,
    Float,
    Sized,
    Unsized,
    Char,
    Str,
    Bool,
    Nil,
    Any,
    BigInt,
    BigFloat,
    List,
    Map,
    Set,
    Tuple,
    UnknownType,
    Struct,
    Enum,
    Import,
    Export,
    Bind,
    Alias,
    Let,
    Change,
    SectVar,
    SectNest,
    Self_,
    SectComplex,
    SectOverride,
    As,
    OpAdd,
    OpSub,
    OpMult,
    OpDivide,
    OpGreater,
    OpLess,
    OpGreaterOrEq,
    OpLessOrEq,
    OpMod,
    OpAnd,
    OpOr,
    OpEqualTo,
    OpNotEq,
    OpBitOr,
    OpBitAnd,
    OpBitNot,
    OpBitRightShift,
    OpBitLeftShift,
    OpBitXor,
    True,
    False,
    IsEmpty,
    IsWhitespace,
    FuncRange,
    FuncStartsW,
    FuncEndsW,
    FuncContains,
    FuncEquals,
    ExclamationPoint,
    Cond,
    UserFunc,
    // Hmm...
    Unknown,
}

impl Display for Formatted {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Formatted::Integer => write!(f, "Integer"),
            Formatted::Float => write!(f, "Float"),
            Formatted::I8 => write!(f, "i8"),
            Formatted::U8 => write!(f, "u8"),
            Formatted::I16 => write!(f, "i16"),
            Formatted::U16 => write!(f, "u16"),
            Formatted::I32 => write!(f, "i32"),
            Formatted::U32 => write!(f, "u32"),
            Formatted::I64 => write!(f, "i64"),
            Formatted::U64 => write!(f, "u64"),
            Formatted::Sized => write!(f, "sized"),
            Formatted::Unsized => write!(f, "unsized"),
            Formatted::BigInt => write!(f, "BigInt"),
            Formatted::U128 => write!(f, "u128"),
            Formatted::I128 => write!(f, "i128"),
            Formatted::F16 => write!(f, "f16"),
            Formatted::F32 => write!(f, "f32"),
            Formatted::F64 => write!(f, "f64"),
            Formatted::F128 => write!(f, "fi128"),
            Formatted::BigFloat => write!(f, "BigFloat"),
            Formatted::Char => write!(f, "char"),
            Formatted::Str => write!(f, "str"),
            Formatted::Bool => write!(f, "bool"),
            Formatted::Nil => write!(f, "nil"),
            Formatted::Any => write!(f, "Any"),
            Formatted::List => write!(f, "List"),
            Formatted::Map => write!(f, "Map"),
            Formatted::Set => write!(f, "Set"),
            Formatted::Struct => write!(f, "struct"),
            Formatted::Enum => write!(f, "enum"),
            Formatted::Import => write!(f, "import"),
            Formatted::Export => write!(f, "export"),
            Formatted::Bind => write!(f, "bind"),
            Formatted::Alias => write!(f, "alias"),
            Formatted::Let => write!(f, "let"),
            Formatted::Change => write!(f, "change"),
            Formatted::SectVar => write!(f, "var"),
            Formatted::SectNest => write!(f, "nest"),
            Formatted::SectComplex => write!(f, "complex"),
            Formatted::SectOverride => write!(f, "override"),
            Formatted::IsEmpty => write!(f, "IsEmpty"),
            Formatted::IsWhitespace => write!(f, "IsWhitespace"),
            Formatted::FuncRange => write!(f, "Range"),
            Formatted::FuncStartsW => write!(f, "StartsW"),
            Formatted::FuncEndsW => write!(f, "EndsW"),
            Formatted::FuncContains => write!(f, "Contains"),
            Formatted::FuncEquals => write!(f, "Equals"),
            Formatted::Cond => write!(f, "condition"),
            Formatted::UserFunc => write!(f, "function"),
            Formatted::Unknown => write!(f, "Unknown"),
            Formatted::Tuple => write!(f, "Tuple"),
            Formatted::Self_ => write!(f, "self"),
            Formatted::UnknownType => write!(f, "untyped"),
            Formatted::As => write!(f, "as"),
            Formatted::True => write!(f, "true"),
            Formatted::False => write!(f, "false"),
            Formatted::OpAdd => write!(f, "+"),
            Formatted::OpSub => write!(f, "-"),
            Formatted::OpMult => write!(f, "*"),
            Formatted::OpDivide => write!(f, "/"),
            Formatted::OpGreater => write!(f, ">"),
            Formatted::OpLess => write!(f, "<"),
            Formatted::OpGreaterOrEq => write!(f, ">="),
            Formatted::OpLessOrEq => write!(f, "<="),
            Formatted::OpMod => write!(f, "%"),
            Formatted::OpAnd => write!(f, "&&"),
            Formatted::OpOr => write!(f, "||"),
            Formatted::OpEqualTo => write!(f, "=="),
            Formatted::OpNotEq => write!(f, "!="),
            Formatted::OpBitOr => write!(f, "|"),
            Formatted::OpBitAnd => write!(f, "&"),
            Formatted::OpBitNot => write!(f, "~"),
            Formatted::OpBitRightShift => write!(f, ">>"),
            Formatted::OpBitLeftShift => write!(f, "<<"),
            Formatted::OpBitXor => write!(f, "^"),
            Formatted::ExclamationPoint => write!(f, "!"),
        }
    }
}
